### ISSUE TITLE
Harpy in end

### ISSUE THREAD

**Issue by GnomTocha** [skyjay1/GreekFantasy#10]
![2020-12-12_09 53 51](https://user-images.githubusercontent.com/75666317/101978808-c8ea5d80-3c68-11eb-9530-3f9af33f693c.png)
Last version mod
![2020-12-12_09 54 13](https://user-images.githubusercontent.com/75666317/101978815-da336a00-3c68-11eb-957b-20397b663d84.png)
![Uploading 2020-12-12_09.54.16.png…]()

**Comment by skyjay1** [comment]
Oops, I guess the End is registered in BiomeDictionary as "DRY". Go into the config and remove DRY from the whitelist in "harpy_spawn" and I'll remove it from the default config file

**Comment by MokahTGS** [comment]
Or add a dimensional blacklist to the config so we can fix this in modpacks.

**Comment by skyjay1** [comment]
Fixed in #12
