### ISSUE TITLE
[1.18.2] Making bronze?  Alloy?

### ISSUE THREAD

**Issue by MokahTGS** [skyjay1/GreekFantasy#103]
Looking at bronze in JEI it can be melted in Tinkers smeltery but there is no way to make bronze.  Bronze isn't an ore, so how do we obtain it in a world that doesn't generate it?

**Comment by skyjay1** [comment]
This is intentional, I wanted to encourage the player to explore.
From the mod description page:
> Bronze - created by melting bronze scrap that is found in chests around the world; used to make armors and summon bosses.

Bronze nuggets are also dropped by cyclopes, I'll add this info to the mod page :)

**Comment by MokahTGS** [comment]
Ah...thanks for that.  I'm making a modpack that features Greek Fantasy and I'll add that to my notes for informing players.
