### ISSUE TITLE
Some ideas for the mod

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#105]
Hey,
I would like to share an idea I got for the mod.
- Adding durability to the conch in the config so it's not an infinite water source
- The choice to Increase the difficulty of all bosses since they feel easy to kill especially the Charybdis
- Harpys being able to respawn in their nests
- All mobs should be able to respawn in their camps so no one is afraid of killing them and losing them forever if they don't always explore outside their area
- The option for server owners to turn off the ability to craft certain items from the config like the totem of undying. why? I feel like an ichor is a better substitute to the emerald in the recipe 
- The option to turn off enchantments from showing up in the librarian villager trades

**Comment by Looodon** [comment]
Another suggestion is increasing the speed of Harpys, they never land a hit because they come at people so slow. They're the easiest to kill in the mod without being hit at all

**Comment by skyjay1** [comment]
> Adding durability to the conch in the config so it's not an infinite water source

I don't see why this is a problem when the ocean is an infinite water source. Can you explain a bit more how this is a useful feature?

> The choice to Increase the difficulty of all bosses since they feel easy to kill especially the Charybdis

Many of the bosses are in fact mini-bosses and are not meant to be super-difficult, but I can improve the Charybdis since this is not the first time I've heard it is too easy compared to its reward.

> Harpys being able to respawn in their nests

Due to Minecraft limitations, this is not currently possible.

> All mobs should be able to respawn in their camps so no one is afraid of killing them and losing them forever if they don't always explore outside their area

Good idea, I'll add that.

> The option for server owners to turn off the ability to craft certain items from the config like the totem of undying. why? I feel like an ichor is a better substitute to the emerald in the recipe

Crafting recipes cannot be modified from config files anymore. Use a datapack or crafting-recipe-tweaker mod.

> The option to turn off enchantments from showing up in the librarian villager trades

Sure, if I have time :)

**Comment by Looodon** [comment]
Thanks for responding! The conch makes the game easier when in dangerous situations underground mining where u can jump from high places or turn off lava with no danger element.

Charybdis ideas: increased damage OR it can use the same code as the lion where it "eats" you and spit you out to do damage OR The whirlpool pull can be more aggressive while causing slow swim OR spawning 5 drowned AND/OR nerfing the reward

For reference regarding the Harpys speed there's a mod called "Hostile Mobs and Girls" that has quicker harpys but its because they can walk as well I assume

All and all, the most important request to me is having the mobs respawn in their camps/naturally so the mod can be enjoyed more without fear of permanently losing them, thank you so much for the great mod!

**Comment by skyjay1** [comment]
This will be included in the next 1.18 and 1.19 releases
