### ISSUE TITLE
Gigante spawn issue

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#107]
Minecraft version: 1.19.2

Hey, the Gigante spawn in mountains for the first time, but once you leave the area and the chunks unload and go back, then they despawn and never spawn again in the same place. If i spawn the Gigante with a spawn egg, leave, and come back they disappear, but when i do it with any other mob, when I leave and come back they are still there.

**Comment by skyjay1** [comment]
This will be included in the next 1.18 and 1.19 releases
