### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#109]
Hey, I just wanna thank you for taking my feedback, your time, and quick responses. I'm a noob when it comes to modding knowledge, but i know how to download the code and turn it into a mod before the mod is released to curseforge. I saw you implemented all the fixes already (#104, #107, #108) but since Im new and don't know how to read github well yet, I wanted to know if I download the 1.19.2 version, will the #105 changes be applied already? If not yet, no problem, I'm genuinely asking, not to rush! Thanks again 🥇

**Comment by skyjay1** [comment]
From #110 I'm guessing you figured it out, but yes, all of #105 has been added except for harpy respawning. I'll try to think of a way to summon/create harpies, for now they spawn (rarely) in deserts.
Conch durability is disabled by default, check the config.

**Comment by Looodon** [comment]
Will do, thank you sm! [🙏](https://emojiterra.com/folded-hands/)
