### ISSUE TITLE
1.19.2 Sapling

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#110]
Forge: 43.1.27
Minecraft: 1.19.2

Hey, I did a little test on the [#796daa](https://github.com/skyjay1/GreekFantasy/commit/796daa608a2d01b5beb13bf39cafcdaf0f1c9795) commit regarding issue #104. Thanks for the fix! I just wanted to give you a heads up (in case it mattters) that the Pomegrante & Olive saplings are fixed, while the Golden Sapling disappears (bug I think). Have a good day and thank you for the great work! 👍

**Comment by Looodon** [comment]
Hey! just wanted to add that after testing the conch that the durability didn't go down for me even after changing the configs

**Comment by skyjay1** [comment]
Make sure you are testing in survival mode, items don't lose durability in Creative mode.
