### ISSUE TITLE
[1.18.2] Compatibility/Crash with Epic Knights mod

### ISSUE THREAD

**Issue by MC-Valdreth** [skyjay1/GreekFantasy#111]
Not sure who's end this is on, but I've narrowed down the incompatibility to these 2 mods.

The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Epic Knights: Armor and Weapons (magistuarmory) encountered an error during the enqueue_imc event phase

Crash Report: https://pastebin.com/chypnmYQ
latest.log: https://pastebin.com/2k3Gbjb0

Forge Version: 40.1.80
Minecraft Version: 1.18.2
Greek Fantasy Version: [18.2.4](https://www.curseforge.com/minecraft/mc-mods/greek-fantasy/files/3940958)

Other Mods Installed: 
Epic Knights Version: [6.6](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons/files/3961249)

Original report on their page: https://github.com/Magistu/Knightly-Armory/issues/17

**Comment by skyjay1** [comment]
This is an issue with Epic Knights mod. They should not assume that modded banners will always have the same naming format.

**Comment by MC-Valdreth** [comment]
I'm a bit late, but this was fixed as of Epic Knights Version: [7.6](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons/files/4403132) Both mods can be used together now.
