### ISSUE TITLE
Some ideas for the mod

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#112]
--------
### EDIT: 
- Added totem recipes on this comment 
- More recipes/info/SpawnWeight in the comments after

--------
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Hey, the mod's great and I'm happy with the changes and updates! 
I thought I'd share some idea's regarding the mod in case you were interested!

The basis of my suggestions are based on how hard are the rewards are to get without fighting the bosses. For example, if netherite takes 1 hour to dig but a boss that drops it takes 8 mins to get the materials to spawn and kill, etc If you make these changes I'll be able to help with sending you the updated wiki explanation!

**MOBS**

- Suggestion: if you ever wanna change the loot of one boss maybe you can give only ONE boss a 20% chance to drop a mysterious box drop chance. This way, Instead of giving them an ichor, they trade for it them self.

After testing some bosses and loot in survival these are the conclusions I came to in my opinion:
1) **Talos**
-Difficulty: 6/10
-Avg Drop: 8 ichor, 10 copper ingots, 13 arrows, 1 Ichor-Infused Gear, and Heart of Talos
-Solution: To reduce ichor drop rate to min 0-1 max + increase HP by 60
-Reasoning: A shield blocks all arrows. ichor can make armor that you can use mending on and never break, ontop of that, ichor costs 1 diamond, so technically a 2 diamond drop is already a lot

2) **Bronze Bull**
-Difficulty: good challenge without fire resistance, but with fire resistance its 2/10
-Suggestion: making his physical attacks more common than the fire might make it more balanced, increase HP by 50
-Reasoning: if you use fire resistance he does almost no damage and he stands on top of you doing nothing, reduce ichor drop to min 0-1 max

3) Charybdis & Scylla
-Difficulty: used to be 2/10 now its 12/10 with Scylla
-Info: Scylla is a great addition to the mod, but it was impossible to physically attack her because of slow swim. The only way to kill her to to shoot arrows at her from FAR where she doesnt see/attack you, which feels like cheating, then physically attack char after killing her. The new Char buff makes it impossible to attack her at all.
-Suggestion: I know we can turn Scylla off from config, but she's a fun boss, why not make her spawn differently?

Solution 1: If you remove her from a spawning Charybdis, she can rarely spawn by shipwrecks, she can appear in oceans/beaches when it rains/thunders, and can be spawned using something like a conch with orthus heads. Her loot be the same as the current one, but you can add 1-5 Prismarine Crystals, and a 10% chance of 3 min water breathing potion.

Spawn example:
![2022-09-Minecraft_ 1 19 2 - Singleplayer-000076](https://user-images.githubusercontent.com/111690606/192705174-7d08393c-6891-4468-93d1-8588b9e03a62.jpg)

Solution 2: She can spawn first where you have to kill her and then the char appears after

Solution 3: OR a 10-20% general small nerf to how it currently is

NOTE: The char's weakness is: placing a block next to him so you're not in water, which makes him deal 0 damage or effects, which Scylla compensates for here with her projectile

4) Geryon
-Difficulty: 5/10 physically. 0/10 with bow
-Avg Drop: 3 diamonds, 1 netherite scrap, 1 club of Smashing, 2 ambrosia, 1 horn of plenty
-Suggestion: 
-make him immune to arrows + make him a bit faster + increase HP by 60-90+
-remove netherite ingot drop (it's too OP), remove netherite scrap drop or reduce it to 10% chance drop of 1, reduce ambrosia to min 0-1 max chance, reduce diamond to min 0-1 max chance
-Reasoning: getting 1 netherite can take someone 1-4 hours, but finding and killing 3 gigante and then killing the boss can take up 5-10 mins. Diamond is also a bit hard to find. 

5) Harpy
-Suggestion: one way to buff harpy is to make them apply levitation for 5 seconds (as if they held you using their bird feet and flew up with you and dropped you) the drop from 5 sec levitation is half a heart.

**SPAWN RATE**

1) Drakaina & Fury
-Suggestion: the Drakaina & Fury spawn rate in the nether is so high I had to lower it so that other mobs can spawn. The sweet spot I found was 

EDIT: Spawn rates moved to a comment down below

**ITEMS**

1) Totem of Undying
The totem can save you from losing loot like full netherite armor, and hours of grinding and its hard to get without a raid in the game so obtaining it should be a bit more costly. I suggest adding diamond or ichor to the crafting recipe to make it more fair

For example of recipes from 1st (best priced) to 6th (cheaper priced)
![totem](https://user-images.githubusercontent.com/111690606/193022584-b5894a0c-04c1-4c4e-a75d-f4b83f2d3132.png)

EXTRA:
1) Slightly increase the HP AND/OR speed of satyr, lampad, dryad, ara, cerberus
2) would be nice to add the ability to turn on durability for Avernal, Apollo, and Artemis bows
3) would be nice to make the thunderbolt and wand of circe lose more durability or having the choice to manually set it

Low Priority:

Compatibility:
1) All your weapons are compatible currently work with the [Better Combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus) mod except the spears, bident, wand/staffs. If its easy to enable it so that their animation works with the mod that would be nice. Since there isn't one for clubs you can use the the heavy_axe animation to the clubs.

FUN:

1) Making Drakaina hostile towards Vex
2) Making Centaur hostile towards Phantoms

**Comment by skyjay1** [comment]
Thank you for the detailed feedback! I'll take more time to read through it carefully, but here are some initial thoughts:

**MOBS**

0. Boss difficulty:
It's tricky to find a balance of "early-game" vs. "end-game" bosses, and I'm not really sure which bosses I want in which category. I'll review how difficult it is to encounter / summon each boss and add more health and/or armor to the end-game ones.
1. Talos: 
I may be misremembering but I thought ichor is only used for the Thunderbolt, Winged Sandals, and Ambrosia. With such limited use, a large amount of ichor is probably not overpowered.
2. Bronze Bull:
I can reduce the cooldown between physical attacks.
3. Scylla: 
she can be summoned alone by using a Wand of Circe on an ocean nymph. This is hinted at in "Quest: Summon and Slay Scylla". You can configure the chance for Scylla to spawn with Charybdis, I'll reduce the default value in the future.
4. Geryon
Good points, I can reduce the loot drops for balancing. 
5. Harpy
Hmm, maybe.

**SPAWN RATES**

Thank you for taking the time to experiment and find a good balance, I'll make these the default weights to save everybody else the trouble :)

**ITEMS**

1. That recipe could make ichor more useful (and justify a reduction on ichor loot from bosses). Golden fleece is difficult to obtain already (requires dragons breath) so I'm not sure the recipe needs to be harder. Also if you have ideas for other uses of the golden fleece, I'm all ears.

**EXTRA**

1. Sounds reasonable.
2. Sounds reasonable.
3. I used to have these as config options in 1.16 but I didn't think anybody used them 😓 I'll add them back

**COMPATIBILITY**

1. After a quick search it looks like I can add compatibility with JSON files, so that's a reasonable request.

**FUN**

1. Sure, why not?
2. Sure, why not?

**Comment by Looodon** [comment]
You're the best! thank you for taking the time to hear out the ideas! Just to respond quickly to some of the things you mentioned:

MOBS

0- Boss Difficulty:
for context, I did my tests wearing full iron, iron sword, shield, and steak as food. A good balancing technique you already use is making the bosses immune to arrows so no one hides out of reach. but also, people always have the support of the Sparti. another thing is a boss loot can be nerfed instead of the boss being buffed for example 

1- Talos:
i view ichor as valuable because i view both Winged Sandals and Ambrosia as legendary items. my sandals have durability cuz they're game changing without it and Ambrosia is like the Notch apple which Mojang makes almost impossible to obtain. but you're right about what you said. In a way, i came from a place that liked to have people spawn the bosses many times to fight than fighting them once in a while

SPAWN RATES

1- if you ever want the rest of the spawn rates I tested I can send them to you soon, my priority was to send the most important ones in my opinion.

ITEMS

1- perfect! I personally don't view dragon breath as rare. It is a late game item for sure but once you enter the end, it becomes an infinite source. The way I play was I would always go with as many bottles and never have to go back again since I enjoy making potions. i'll look into more uses for fleece and get back to you! 

That's all. Again, thank you so much!

**Comment by Zacknpa100** [comment]
i have a suggestion perhaps turning the thunder bolt into a throwable lightning bolt a 3D model perhaps? same exact enchantment except you throw it and it strikes where it lands and perhaps something cool happens when you throw it into the sky

**Comment by Looodon** [comment]
GOLDEN FLEECE RECIPES 

1- Its purpose can be to be used to revert *some* items to their original state while keeping in mind ways to avoid making it game breaking. Like removing enchantments, or "cleaning" the obsidian block, or cleaning arrows. Examples:

![reci2](https://user-images.githubusercontent.com/111690606/192948562-148f2aba-d84e-48fd-83d1-b955cbc22fbd.png)

2- instead of number 1, its purpose can be functional. One thing you can do is removing the tooth+sapling recipe and replace it with fleece. Like these examples:

![Reci1](https://user-images.githubusercontent.com/111690606/192948524-75cb7e1d-09e0-4fd3-9edb-8c4293366780.png)

3- instead of number 1 & 2, its purpose can be for horses, you can make it so that you can only ride Pegasus with a golden saddle (i did a rough sketch). Also making golden horse armor craftable. Example:

![1](https://user-images.githubusercontent.com/111690606/192949214-c2a49baa-8ad1-4061-a7a0-2348cbe6d8cb.png)

4- instead of numbers 1 & 2 & 3, its purpose can be to turn the fruits into their golden version, but personally I don't like that cuz it would be better for fleece to have a unique function than replacing gold ingots

![2](https://user-images.githubusercontent.com/111690606/192949620-d0dee0a7-b840-455a-91bf-81b1e0bbd58f.png)

AUTOMATON

-After finding out what automaton does, I did some test, I know that in order to spawn him, you would have had to kill bosses prior, you know me by now LOL, I feel like it might nice to add some balance. I feel like he's indestructible, I spawned Automaton, and it killed Talos, and multiple other bosses without dying. This can be abused to farm more automatons.

These suggestions dont all have apply, but multiple can at the same time: 
-Make Automatons not attack any bosses, he can instead just attack regular naturally spawning hostiles.
If you don't like this idea, at least consider making him not hostile to Talos/BronzeBull (metallic bosses) 
-Remove the self-regen, if someone wants to heal Automaton, then use ichor on it to heal 20 health
-Lowering health to 130, ik this is a big HP nerf, but that means, people fight more bosses, and play the mod more
-Maybe make it rust/damage/slow from water/rain? idk how I feel about this one, but some sort of weakness
-Maybe adding a timer until it dies, maybe 5 minutes? maybe using ichor on it extends its time?
-(unlikely and random thought I had) Another thing could be that he stays still, but only attacks hostiles if you're holding a certain item while 5-8 blocks near him or while wearing a certain item. OR if he has a certain splash potion effect applied to him only would he then he becomes hostile to hostile mobs

Its immune to arrows is already a massive advantage. His indestructability has high abuse potential for farming anything
![auto](https://user-images.githubusercontent.com/111690606/192952239-8af84b88-5e6a-4aaa-979e-d07429c61326.gif)

**Comment by Looodon** [comment]
These are the spawn weights (more of less) I came up with for best experience in my opinion to experience the best balance of the mobs. In alphabetical order. (Mob name, Weight,  Min,  Max)

### UNCHANGED

ara
centaur
mad_cow
orthus
stymphalian

### CHANGED

empusa, 24, 1, 2 (they still spawn a good amount)
cerastes, 24, 1, 3 (to allow for desert diversity)
cyprian, 19, 2, 4
cyclops, 25, 2, 5
fury, 6, 1, 2 (to make them less over-crowded)
gigante, 8, 1, 2 (to make them less over-crowded)
gorgon, 19, 1, 2
harpy, 17, 2, 5 (for desert diversity)
lampad, 26, 2, 5
minotaur, 27, 2, 5 (they still spawn a good amount)
naiad, 14, 2, 5
pegasus, 3, 3, 3 (they used to spawn way too often)
shade, 3, 1, 1 (they still spawn a good amount)
siren, 15, 2, 4 (they didn't spawn enough)
unicorn, 15, 3, 4
whirl, 14, 1, 1 (were too hard to find one)

### Per biome

_drakaina_ (to make them less over-crowded)
Overworld: 20, 1, 2
Nether: 11, 1, 2

_dryad_ 
Overworld: 25, 2, 4
Forests: 27, 2, 4

_satyr_
Overworld: 23, 2, 5
Forests: 25, 2, 5

**Comment by skyjay1** [comment]
I have added most of these suggestions in Greek Fantasy 19.2.3 (which will be available on CurseForge soon). I added one or two more uses for Golden Fleece but I will keep thinking about it and the other recipe suggestions.

**Comment by Looodon** [comment]
You're a legend! thank you for all the great work!
