### ISSUE TITLE
3 Bugs

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#113]
Bug 1: The conch config for durability is not working even in survival, I set it to 64 and nothing changes

Bug 2: Some of the potions and arrows names are incorrectly displayed:
(there are other ones not included in the GIF below)
![2022-09-28 12-32-22](https://user-images.githubusercontent.com/111690606/192730880-7d2e9e1f-0b03-499c-8394-2aab4dbdf7d2.gif)

Bug 3: the Automaton spawns, but doesn't move or attack me at all. He spawns with a weird name:
![2022-09-Minecraft_ 1 19 2 - Singleplayer-000083](https://user-images.githubusercontent.com/111690606/192730703-a40d8655-9d19-4230-ba10-2bf5ade306e0.jpg)

**Comment by skyjay1** [comment]
The automaton is friendly and fights monsters like an Iron Golem, but does not wander around. This is intentional.

I'll update the translation file
