### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Looodon** [skyjay1/GreekFantasy#116]
Heyy,
Loving the update so far, I just wanted to let you know that I found two bugs

1) All the weapon durabilities work except for all the bows. (GIF attached)

2) When in survival mode only, holding the thyrsus crashes the game when you left click any block. (image attached)

3) Not a bug, but what does "thunderbolt_durability_on_fireflash" do?

Here's the crash report:
https://paste.gg/p/anonymous/711501bb3e474848bc2a3b9a6c507182

1st - GIF of Bows:
![2](https://user-images.githubusercontent.com/111690606/194103515-15747211-f633-4c33-aa8c-6476ba3f365e.gif)

2nd - There's even a warning at the top (jade mod). When in creative mode there's no warning and the bug doesn't happen

![1](https://user-images.githubusercontent.com/111690606/194096873-d2967e9b-6de9-44de-8691-c90a2701a802.png)

**Comment by skyjay1** [comment]
3. The thunderbolt uses a different amount of durability when it is enchanted with Fireflash (only obtainable in survival mode when RPG Gods is also installed)

**Comment by skyjay1** [comment]
I see a lot of Better Combat mixins at the crash location, does this crash occur without Better Combat installed?

**Comment by Looodon** [comment]
This is the crash report after removing all mods except GreekFantasy: 
https://paste.gg/p/anonymous/03aa6e0482124ff28aa787a1f4ef909e
