### ISSUE TITLE
Greek Fire Transparency Broken

### ISSUE THREAD

**Issue by Kuusotare** [skyjay1/GreekFantasy#117]
I currently play with Rubidium and Oculus installed, and Greek Fire transparency seems to be bugged. I play on 1.19.2.

**Comment by skyjay1** [comment]
Greek Fire is not transparent. This is not an issue.

**Comment by Kuusotare** [comment]
> Greek Fire is not transparent. This is not an issue.

Hi,

It is an entire block's worth of blue textures. A blue cube more or less, rather than the appearance of fire. So yes, the transparency in its appearance is broken. I am happy to send you screenshots if you'd like.

**Comment by skyjay1** [comment]
Please send images, I'm not sure I understand what you mean

**Comment by Kuusotare** [comment]
> Please send images, I'm not sure I understand what you mean

I will do this as soon as I'm home to hopefully better illustrate it. Basically, in addition to the fire texture, all of the empty transparent "air" that would normally appear in the space on the block is filled with a solid blue texture, as if it's a complete solid block of blue with a moving fire texture on it.

**Comment by Looodon** [comment]
This happened to me a while back, but not anymore. idk what fixed it, but make sure all the mods are updated to the latest version. I also have Rubidium Extra, but it could be something that has to do with the settings from these mods. We can compare settings if that'll help you find out the issue. Try to see if removing these mods one by one fixes the fire to know which one exactly

**Comment by Kuusotare** [comment]
I've just uninstalled every mod except Greek Fantasy and attempted to use Greek Fire once again, and had the exact same issue.

I use Forge 43.1.32 for 1.19.2 and have this issue even with Greek Fantasy as the only mod installed. No graphical modification mods.

https://i.imgur.com/JjxoII4.png

**Comment by Looodon** [comment]
I did some testing, it turns out one of the shaders I had was what solved it. Ill edit this if I find out more info

![22-min](https://user-images.githubusercontent.com/111690606/194272479-f7e63900-e527-46bc-9e24-476956a93a0c.png)

**Comment by skyjay1** [comment]
I was able to replicate the issue, but for some reason the texture is transparent only when the fire is on water. I'll look into it.
