### ISSUE TITLE
1.19.2 Crash on startup

### ISSUE THREAD

**Issue by Kuusotare** [skyjay1/GreekFantasy#118]
Currently the latest version of Greek Fantasy crashes on statup, both client and server, if Canary is also installed.

Removing either mod fixes the issue. However, Canary and similar mods have become must-haves in the current modding ecosystem.

The latest version also seems to introduce a new crash with Werewolves. Removing Greek Fantasy fixes the issue.
https://pastebin.com/zP55vdHY

**Comment by skyjay1** [comment]
> Currently the latest version of Greek Fantasy crashes on statup, both client and server, if Canary is also installed.

Please provide a crash report for this issue as well

**Comment by Kuusotare** [comment]
> > Currently the latest version of Greek Fantasy crashes on statup, both client and server, if Canary is also installed.
> 
> Please provide a crash report for this issue as well

If I recall correctly it simply spat exit code 1 and didn't generate a crash log. I will double check this later today, and if I find more I will submit it here to help as best I can.

**Comment by skyjay1** [comment]
if you see an exit code, open your minecraft folder and locate `logs/debug.log` which will have all the information I need. Thank you :)

**Comment by skyjay1** [comment]
Please report the Werewolves crash to the developers of that mod, I don't see anything in the crash report to indicate it is something I can fix.

**Comment by Looodon** [comment]
I had to remove Canary because it was causing crashes and chunks to not load correctly or at all. Once I removed Canary my issues got resolved, Canary kinda did more bad than good for me for some reason (this was before the new greek update)

**Comment by Kuusotare** [comment]
https://pastebin.com/91h4sMMg

**Comment by skyjay1** [comment]
Unfortunately nothing in the log mentions Greek Fantasy. The last lines of the log are from Canary loading mixins, one of them must have failed somehow.

**Comment by Kuusotare** [comment]
> Unfortunately nothing in the log mentions Greek Fantasy. The last lines of the log are from Canary loading mixins, one of them must have failed somehow.

Well, the best insight I can provide is that a change between the latest and the previous Greek Fantasy 1.19.2 version introduced the bug, as downgrading Greek Fantasy solved the issue completely.

**Comment by skyjay1** [comment]
I hope it's not an issue with the Better Combat compatibility that I added.

**Comment by Looodon** [comment]
### Test 1:
Minecraft 1.19.2 
forge 43.1.27 
Latest version of Canary 
Latest version of GreekFantasy
**Result =** no crash, worked as intended.

### Test 2:
Minecraft 1.19.2 
forge 43.1.33 <--- _(updated to latest version of forge)_
Latest version of Canary 
Latest version of GreekFantasy
**Result =** no crash, worked as intended.

### Test 3:
Minecraft 1.19.2 
forge 43.1.33
Latest version of Canary 
Latest version of GreekFantasy
+With ALL other mods removed
**Result =** no crash, worked as intended.

**Comment by Kuusotare** [comment]
I just did a test with only Greek Fantasy and Canary and confirmed that there was not a crash. However, using only Greek Fantasy, BetterCombat, and its dependencies results in a crash. 

So, it seems that the actual conflict is between Greek Fantasy and BetterCombat.

https://pastebin.com/VBM9cPNz

**Comment by Looodon** [comment]
### Test 1
Minecraft (1.19.2)
Forge (43.1.33)
● Bettercombat (1.4.4)
● Plus its dependency: PlayerAnimator (0.4.0)
● Canary (0.0.3)
_+72 mods_
**Result = no crash, worked as intended.**

### Test 2
Minecraft (1.19.2)
Forge (43.1.33)
● Bettercombat (1.4.4)
● Plus its dependency: PlayerAnimator (0.4.0)
● Canary (0.0.3)
_+With ALL other mods removed_
**Result = no crash, worked as intended.**

Can you try loading the game with an empty config folder? maybe also share your mods list? I feel like it might be another issue

**Comment by Kuusotare** [comment]
It appears I hadn't updated BetterCombat. Doing so fixed the issue. Thank you for double checking.

**Comment by skyjay1** [comment]
Thank you Looodon for the thorough tests :) I'm glad to hear I didn't bork Better Combat haha.
