### ISSUE TITLE
Start up client crassh

### ISSUE THREAD

**Issue by drwad** [skyjay1/GreekFantasy#121]
[crash-2022-10-18_10.52.45-client.txt](https://github.com/skyjay1/GreekFantasy/files/9811116/crash-2022-10-18_10.52.45-client.txt)

**Comment by skyjay1** [comment]
Duplicate of #111 
Please inform the Epic Knights developers that it is not safe to convert modded banner names to resource locations.

**Comment by drwad** [comment]
thanks for reply
