### ISSUE TITLE
Greek Fantasy Loading Error

### ISSUE THREAD

**Issue by Avocado873** [skyjay1/GreekFantasy#124]
Whenever I load this mod, the minecraft window loads and says this mod has failed to load correctly. I did have other mods, but it would say this even though if it was standalone. Crash: 
[crash-2022-10-22_15.37.52-fml.txt](https://github.com/skyjay1/GreekFantasy/files/9845155/crash-2022-10-22_15.37.52-fml.txt)

**Comment by skyjay1** [comment]
Duplicate of #122 
Did you even read the solution? Update Forge to `43.1.23` or higher
