### ISSUE TITLE
1.19.2 crash

### ISSUE THREAD

**Issue by Thisguyneedshelp** [skyjay1/GreekFantasy#125]
heres the crash log https://mclo.gs/PFltY11

**Comment by skyjay1** [comment]
Does the crash happen with GreekFantasy by itself, without any other mods installed?

**Comment by skyjay1** [comment]
Unable to reproduce. Launching Greek Fantasy 19.2.5 with Forge 43.1.47 does not result in a crash.

**Comment by Thisguyneedshelp** [comment]
yeah sorry, theres over 350 mods in the modpack at this point and i dont think ill be able to pinpoint exactly which one it is
