### ISSUE TITLE
1.19.2 Accessing LegacyRandomSource from multiple threads Crashes

### ISSUE THREAD

**Issue by NotCvmo** [skyjay1/GreekFantasy#126]
I run a server for my friend group and have recently encountered a few crashes that seem to originate from this mod. The mod pack is Medieval MC ([Link to server pack](https://www.curseforge.com/minecraft/modpacks/medieval-mc-forge/files/4062424)). Plus a few extra mods we decided to add.

I am attaching the two most recent crash logs which are a result of a mob/structure from this mod.
Crash description (same for both files): ```Accessing LegacyRandomSource from multiple threads```
Line 160 of crash1.txt: ```"Description: ResourceKey[minecraft:worldgen/structure / greekfantasy:cyclops_cave]"```
Line 160 of crash2.txt: ```"Description: ResourceKey[minecraft:worldgen/structure / greekfantasy:ocean_village]"```

I will most likely disable the mod for now if it continues to crash, but I figured it may be helpful to report it here anyways.

Thanks!
[crash1.txt](https://github.com/skyjay1/GreekFantasy/files/9932080/crash1.txt)
[crash2.txt](https://github.com/skyjay1/GreekFantasy/files/9932081/crash2.txt)

**Comment by skyjay1** [comment]
Thanks for the detailed info and crash reports. I'll upload a fix soon.

**Comment by NotCvmo** [comment]
> Thanks for the detailed info and crash reports. I'll upload a fix soon.

No worries! If you need any more info about my specific environment I will be happy to provide anything, just let me know.

**Comment by skyjay1** [comment]
Please try [Greek Fantasy 19.2.6](https://www.curseforge.com/minecraft/mc-mods/greek-fantasy/files/4066828) and let me know if the crash continues.
