### ISSUE TITLE
[1.16.5]Potion transformed into mirroring

### ISSUE THREAD

**Issue by DoctorMage** [skyjay1/GreekFantasy#128]
No idea on why it happens did test alex's mobs potions but they were fine
https://streamable.com/6zvwod

Forge 36.2.39
ars_nouveau-1.16.5-1.25.10.jar
greekfantasy-16.5.5.jar
geckolib-forge-1.16.5-3.0.106.jar
curios-forge-1.16.5-4.0.5.3.jar

Attempting to make either spell damage or mana potion long form turns them into a mirroring potion

Reported to both mods invovled gits

**Comment by skyjay1** [comment]
The 1.16.5 version of the mod is no longer receiving updates. However, you can try turning off the Mirroring potion in the config to see if Greek Fantasy is the problem.
Here is the relevant code for the other mod: [GFRegistry.java#L1341](https://github.com/skyjay1/GreekFantasy/blob/master-1.16/src/main/java/greekfantasy/GFRegistry.java#L1341-L1357)

**Comment by DoctorMage** [comment]
![image](https://user-images.githubusercontent.com/85318453/217104524-6cc6f54f-3d8e-42a8-a077-43f25de45063.png)

For now will just disable both potions since mirror has enchant alt

no clue on what could cause this since it only seems to occur with ars and greek fantasy

**Comment by DoctorMage** [comment]
https://github.com/Gogo08190/chroma-endless/issues/8

seems to be an issue on ars end

**Comment by Natedogwoooof** [comment]
dose anyone know how to set { if (world.isRemote) return; } in the mods mobs class files i am editing it to fix it for personal use but idk anything aboult java and codeing i found out what it is but idk where and how to implamint the code help would be appretated even though im on forge 1.16.5 i just want to fix invalid morph pig thx  for the dryad morph more morphs are effected though
