### ISSUE TITLE
Editing config files

### ISSUE THREAD

**Issue by miguelgamito** [skyjay1/GreekFantasy#129]
Hey. im basically a newbie on this and i dont know where can i find the config files, for example,of the mobs health and life, i decompressed the .jar file and found the .class of the mob but i cant find the parameter of health and all of that stuff, also idk how to stop the generation of some structures like satyr camp and small shrine, since i dont find their spawn rates anywhere else.
If anyone can help me i will be so thankful
![proof](https://user-images.githubusercontent.com/117811192/218075841-a8071433-e0e0-45e3-bd41-512b31e4ef4f.png)

**Comment by skyjay1** [comment]
There are no config options for mob health.

What version of Greek Fantasy is this? In 1.16.5 there is a config file (that does not require decompiling the mod) where you can change structure spawn rates. In 1.18+ you are required to make a datapack for that due to internal changes to Minecraft.

**Comment by miguelgamito** [comment]
So if someone wants to change something related to mobs stats, how you do?
Bcs till i know there should be some files that specify the mob stats, or
am i wrong? Thank you in advance

**Comment by skyjay1** [comment]
There is no easy way to change mob stats in modern Minecraft due to internal changes to the game. Maybe you can find a mod that allows you to change stats of any creature, if such a mod exists
