### ISSUE TITLE
[1.19.2] game doesn't load

### ISSUE THREAD

**Issue by Omega58** [skyjay1/GreekFantasy#136]
I recently downloaded the most recent version of Greek Fantasy for 1.19.2, and every time I load the game, it says that the mod failed to load correctly, using version 19.2.6 . so after that, i downloaded the previous version, 19.2.5 and the gamer did the SAME thing. i reloaded the game multiple times for both versions of greek fantsay, and it can't load correctly every time.
I know the mod hasn't been updated in a long time, but please fix this.

**Comment by Omega58** [comment]
[2023-04-13-10.log.gz](https://github.com/skyjay1/GreekFantasy/files/11231398/2023-04-13-10.log.gz)
here is the log
if it doesn't work message me ASAP

**Comment by skyjay1** [comment]
The log you sent does not have any information about Greek Fantasy failing to load, it looks like an archived log of successfully loaded gameplay. Please reproduce the error and then send the `debug.log` or `latest.log`

**Comment by Omega58** [comment]
[latest.log](https://github.com/skyjay1/GreekFantasy/files/11274442/latest.log)
I've done exactly as you said this time (i deleted my other reply because I didn't do it correctly)

**Comment by skyjay1** [comment]
Update Forge to 43.1.8 or later (preferably 43.2.0 or above)
