### ISSUE TITLE
Mod book

### ISSUE THREAD

**Issue by itsdeadfrosty** [skyjay1/GreekFantasy#137]
Any chance we can get a mod book that explains a little bit about the creatures and characters and mechanics and such? Similar to Apotheosis or echologics, how they all have. Books the character can craft to find out more about the mod. While I am aware that the GitHub page does have a description. Not all players are going to know that they can even go there. To find out info about the mod, and even the curse Forge page does not have much description. Like the GitHub page does.

**Comment by Junkyard-Aristocrat** [comment]
I'd second this. Or at least a wiki page that is more extensive. I feel like I'm flying a bit blind in this mob. I just spend a very long time trying to find altars in the wild so I could get all the (currently in the mod) gods because I didn't see any crafting recipe in JEI or online.
