### ISSUE TITLE
[Suggestion] Lowering all mob spawns

### ISSUE THREAD

**Issue by BugmanBugman** [skyjay1/GreekFantasy#138]
I think mobs spawn a bit too frequently compared to other mobs, so maybe they should all be tweaked to spawn less for their default settings.

**Comment by lSherozl** [comment]
I agree, im kind of surprised the config does not have an option to lower mob spawns for 1.19.2 like 1.16.5 did

**Comment by skyjay1** [comment]
Mob spawns can no longer be controlled by config as of 1.18.2 due to Minecraft and Forge changes. Use a data pack to adjust the [biome modifiers](https://github.com/skyjay1/GreekFantasy/tree/master-1.19/src/main/resources/data/greekfantasy/forge/biome_modifier/spawn) with your own weights.
