### ISSUE TITLE
Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#15]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Greek Fantasy v16.4.4`

It would be interesting to see waterlogging for the Pillars, vase, mysterious box, statues, and the Harpy Nest. All would make for good underwater decorations.

Also, a minor bug with the reeds, if it is broken from the top half, the water in the bottom half is deleted.
(The iron club is also invisible in the hand)

**Comment by skyjay1** [comment]
I'll start adding some waterlogging to the blocks, thanks for the suggestion.
As for the reeds, they act funny when in creative mode but should be ok in survival mode.

**Comment by WenXin20** [comment]
Alright, thanks!

**Comment by skyjay1** [comment]
Also for the iron clubs: it has a really slow charge-up, so it takes a couple seconds to "lift up" when selecting it in the hotbar. Is that what you mean? Or is it not rendering at all?

**Comment by WenXin20** [comment]
It's not rendering at all for me, neither the item nor in the hand. The wood club renders fine though.On Dec 21, 2020 10:21 PM, Skyler James <notifications@github.com> wrote:
Also for the iron clubs: it has a really slow charge-up, so it takes a couple seconds to "lift up" when selecting it in the hotbar. Is that what you mean? Or is it not rendering at all?

**Comment by skyjay1** [comment]
Closing because I finished adding waterlogging to the non-solid blocks. If the latest version still has problems with the iron club, please open a separate issue for it.

**Comment by WenXin20** [comment]
Alright, thanks!
