### ISSUE TITLE
Floating Campsite

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#17]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Greek Fantasy v16.4.4`

Campsites and other structures sometimes generate partially floating. Jigsaw blocks could help prevent this, similar to how villages and pillager outposts can merge with the terrain below to prevent floating buildings. The `/locate` command also does not work with structures from this mod.

![2020-12-21_12 04 35](https://user-images.githubusercontent.com/12000593/102807895-22e3d500-4385-11eb-926e-60a689f13fbb.png)

**Comment by skyjay1** [comment]
Yeah, I haven't gotten around to learning how to use jigsaw yet... right now all of the features are registered as one-shot decoration features instead of structures (which is one reason it doesn't work with /locate)

**Comment by WenXin20** [comment]
Ah, ok, I'm working on learning how to do that myself too.

**Comment by WenXin20** [comment]
![2021-05-11_23 22 55](https://user-images.githubusercontent.com/12000593/117918133-1b7b8480-b2b0-11eb-879f-45529b10a8cf.png)
Found this, it doesn't look very good. It's also spawning in deserts and mushroom biomes still, despite the types `SANDY` and `MUSHROOM` being blacklisted.

**Comment by skyjay1** [comment]
Fixed in 1.18.2
