### ISSUE TITLE
[1.16.4] Charybdis Spawns don't seem to listen to config numbers - Also Peaceful does nothing

### ISSUE THREAD

**Issue by MokahTGS** [skyjay1/GreekFantasy#18]
Version: greekfantasy-16.4.4

Changing the spawn numbers in the config does not seem to lessen the amount of Charybdis spawns...or anything in the sea for that matter.  Also changing the game to peaceful does not stop them spawning.

Basically will have to turn them off.  They spawn all the time.

**Comment by skyjay1** [comment]
I've added despawn-in-peaceful but even if the spawn chance is very low, there are very few things that *can* spawn in the ocean so the Charybdis will turn up sooner rather than later.
Closing anyway.

**Comment by MokahTGS** [comment]
There has to be a way to turn down the spawn rate...we will have to keep them turned off then...

**Comment by MokahTGS** [comment]
I'd like to suggest that you add an option to this mob in the config that allows a summon of Charybdis instead of in world spawning.  Perhaps dropping something into the sea would summon it.

**Comment by skyjay1** [comment]
Closing because Whirl now spawns naturally instead of Charybdis
