### ISSUE TITLE
Invisible Iron Club

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#22]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Greek Fantasy v16.4.5`

The Iron Club is neither rendering the item nor in the hand. The wood club renders fine though.

![2020-12-26_18 57 17](https://user-images.githubusercontent.com/12000593/103161759-3d1a1a80-47ac-11eb-9647-cbe74378bd38.png)

**Comment by skyjay1** [comment]
What other mods are you using? Or is the screenshot from another occasion?

**Comment by WenXin20** [comment]
Here's a list, unfortunately, it's not a small list. I tested the mod on its own and with Optifine/Optiforge, but they're not causing it. What's strange is that the other clubs render perfectly fine, but iron doesn't. Maybe its a server-side issue?

**Comment by skyjay1** [comment]
Is this still happening in the latest version?

**Comment by WenXin20** [comment]
Yep, still invisible.
