### ISSUE TITLE
Cerberus won't summon 

### ISSUE THREAD

**Issue by Chancho91** [skyjay1/GreekFantasy#23]
Minecraft: 1.16.4
Forge: 35.1.13
Mod: 16.4.5
I built the open frame in the right dimensions and filled the gap with lava, I then threw the Orthus head in but nothing happened. I tried it in the Overworld and the Nether, but neither worked.

**Comment by skyjay1** [comment]
I have no problems summoning the Cerberus on my end. Make sure that the frame blocks match the ones in [valid_cerberus_frame](https://github.com/skyjay1/GreekFantasy/blob/master/src/main/resources/data/greekfantasy/tags/blocks/valid_cerberus_frame.json) and that there is air directly above the lava.

**Comment by lordeyahyahyah** [comment]
![cerberus](https://user-images.githubusercontent.com/76751624/103312097-0af5fc00-49ea-11eb-817c-0d8842c232c0.png)

4x4 Polished Blackstone. 2x2 lava. Orthus head thrown in, nothing. Playing the most recent version.

**Comment by skyjay1** [comment]
The only thing I can think of is if the server tick rate is slow, then the head probably made it to the bottom of the lava before checking for a frame. I'll make sure it checks above it as well in the next update.

**Comment by lordeyahyahyah** [comment]
Sounds great looking forward to it, thanks!

**Comment by skyjay1** [comment]
Should be fixed in the latest version. Please re-open this issue if there are still problems.
