### ISSUE TITLE
[Suggestion]: Additional Biome Whitelist

### ISSUE THREAD

**Issue by Tyrius1** [skyjay1/GreekFantasy#24]
Hey so i've been working with the latest versions of the mod. Trying to get used to using the biome type whitelists. Sometimes it's just too broad an approach though. So i was wondering if you could add the old modid:biome whitelist back in as an additional input. 

One example is i'd prefer that unicorns only spawn in the flower forest but with just biome type that is not possible. 

https://www.curseforge.com/minecraft/mc-mods/alexs-mobs <-- This mod actually has a wonderful format for it's biome whitelists.
I didn't like it at first but it is an amazing approach giving us the ability to use not only biome type but also climate and even biome registry.(i believe that's what the format of modid:biome is called?)

**Comment by Yourname942** [comment]
Please add this featrure!
