### ISSUE TITLE
Hostiles spawning in mushroom biomes

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#25]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Greek Fantasy v16.4.5`

Hostile mobs, including Harpy Nests, are spawning in the mushroom biomes, which is meant to be a peaceful only biome.

**Comment by skyjay1** [comment]
I'll add MUSHROOM to the blacklist for hostile mobs but in the meantime you can add it yourself in the config.

**Comment by WenXin20** [comment]
Alright, thanks
