### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#26]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Greek Fantasy v16.4.6`

My server crashed after updating to the new version.
[Crash Report](https://gist.github.com/WenXin20/e904826602b04b569195e00d310d4131#file-greek_fantasy_crash-txt-L32)

**Comment by skyjay1** [comment]
Oops. I imported the wrong ImmutableMap in that file, the next release will have it fixed. Probably in a few days so I can get other feedback. What version of Java do you have?

**Comment by WenXin20** [comment]
I think I'm using 8
