### ISSUE TITLE
Olive tree grows through blocks

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#29]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Greek Fantasy v16.4.7`

When the olive tree is spawned during world gen or grown from a sapling, it'll destroy any block above it, including bedrock.

The biome is also missing localization, which is used by maps.

**Comment by skyjay1** [comment]
Fixed for 1.18+

**Comment by WenXin20** [comment]
Thanks!
