### ISSUE TITLE
mouseClicked event handler error

### ISSUE THREAD

**Issue by Shenra123** [skyjay1/GreekFantasy#34]
I don't think this is supposed to happen but I'm not sure. I wanted to turn off the olive tree, marble, and limestone generation in the configs. I looked at the "chance =" and I set it to 0 for each thinking that would turn it off. When I loaded in and clicked on the "Create New World" button or tried to load a world it would crash with the crash report I included. The range in the configs says I can set it from 0-1000 which is why I think this is unintentional. I can set the olive forest weight to 0 without crashing also. What I did to accomplish what I intended then was to modify the biomes types so no biomes are approved for these three to show up which worked but it felt like a work around.

[crash-2021-02-05_20.50.19-client.txt](https://github.com/skyjay1/GreekFantasy/files/5935775/crash-2021-02-05_20.50.19-client.txt)

**Comment by skyjay1** [comment]
Oops, I should have looked at this before releasing a build today. I think I found where the problem is happening (divide by zero = bad) so for now set it to 1 and they will only have a 0.1% chance of spawning. Sorry for the inconvenience

**Comment by Shenra123** [comment]
No problem, I'm glad you found a fix. I like your mod btw, it makes my worlds feel more full and lived in.
