### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#36]
`Minecraft v1.16.5`
`Forge v36.0.7`
`Greek Fantasy v16.5.12`

My server crashed after loading the new version.
[Crash Report](https://gist.github.com/WenXin20/c41b540963a7a7c0ed3cbb02e794d2d2)

**Comment by skyjay1** [comment]
Similar to #26 , sorry about that. Should be fixed in Greek Fantasy 16.4.13

**Comment by WenXin20** [comment]
Thanks
