### ISSUE TITLE
ores

### ISSUE THREAD

**Issue by nab6969** [skyjay1/GreekFantasy#37]
when i break an ore it doesn't drop the item.

**Comment by marine0f1** [comment]
I've run into this issue as well, it seems to only be affecting nether ores, both modded and vanilla.

**Comment by skyjay1** [comment]
I thought this was fixed in build 16.4.13, which version are you using?

**Comment by marine0f1** [comment]
I was using .12, I installed the mod 3 like days ago, and forge never alerted me of the update. Manually installed it just now, and its working fine. Sorry for the scare!
