### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by Tyrius1** [skyjay1/GreekFantasy#4]
MC 1.16.3
forge-34.1.42
greekfantasy-16.3.2

Noticed some magor entity lag.
I made a fresh profile with just Greek Fantasy and it still happened.
I tested by loading fresh worlds and teleporting to a snowy tundra biome and could visually see it with F3

**Comment by Bidgam** [comment]
I think it's coming from the rabbits and other creatures that are 'rabid' or 'mad' like the Mad Cow. I don't see a config to turn the feature off, but if you go to snowy biomes where those rabbits are, the ticks shoot up.

**Comment by Tyrius1** [comment]
i believe this may actually have something to do with the new launcher. I also noticed a massive amount of openGL spam in logs since the transition and i just opened a fresh profile with GDLauncher and the log spam is gone.

**Comment by skyjay1** [comment]
I've been looking into this issue and found a problem where I'm running some code whenever the game checks if a rabbit can spawn, when in reality the code only needs to be run when a rabbit actually spawns. Hopefully the next release will fix this.

**Comment by skyjay1** [comment]
(Probably) fixed in release 16.4.3. Feel free to re-open this issue if you're still having problems, though
