### ISSUE TITLE
mirror recipe isnt working

### ISSUE THREAD

**Issue by MarmitePeanut** [skyjay1/GreekFantasy#40]
I have only just started using this mod pack and was wanting to craft the mirror however the recipe doesnt seem to work any help would be great. using 1.16.4

**Comment by skyjay1** [comment]
The crafting recipe is one glass pane on top of one gold ingot. See [mirror.json](https://github.com/skyjay1/GreekFantasy/blob/master/src/main/resources/data/greekfantasy/recipes/mirror.json).
Let me know if you still have problems

**Comment by egeskjold** [comment]
Even with the recipe it isn't working for me. I can't make the mirror.

**Comment by skyjay1** [comment]
You're not using the "mineshafts and monsters" mod pack by any chance, are you?
I just learned that some of the Greek Fantasy recipes are changed by that modpack.

**Comment by egeskjold** [comment]
> You're not using the "mineshafts and monsters" mod pack by any chance, are you?
> I just learned that some of the Greek Fantasy recipes are changed by that modpack.

Ooh, yes I am! That explains it then, but is it just different or is it not possible to make it at all?

**Comment by skyjay1** [comment]
> Ooh, yes I am! That explains it then, but is it just different or is it not possible to make it at all?

I wouldn't know. You would need to ask the modpack maker.
