### ISSUE TITLE
MASSIVE CRASHES

### ISSUE THREAD

**Issue by WelpSTudent** [skyjay1/GreekFantasy#43]
Spent all day doing the binary method to try and find the reason for game crashes of loading chunks. You mod is not saying he is responsible but after elimitating 160 mods and having around 10 left, issue goes away by removing GreekFantasy. Adding it back, the issue comes back. Here is the crash report. I do not know what your mod is doing but all I can say is it isn't doing it right lmao.
https://pastebin.com/r671w4LS
Forge: 36.0.61
Version: 16.5.15
https://gist.github.com/celsiusqc/2bf70a637d922e561d745d99b934b8b7
^^ Is an earlier debug, there might be a clue in there somewhere.

**Comment by skyjay1** [comment]
May be related to #39, but maybe not. Were you near a jungle biome? I only have one structure that uses spawners, the Python Pit.

**Comment by celsiusqc** [comment]
I the end and in the overworld. The changes I did were both in configs and a datapack. I removed almost all spawns from the mod and all the structures.

**Comment by skyjay1** [comment]
Are you still having this issue with version 16.4.18?
