### ISSUE TITLE
[1.16.5] Lion den structure is not properly registered

### ISSUE THREAD

**Issue by Febilian** [skyjay1/GreekFantasy#46]
[Blame](https://www.curseforge.com/minecraft/mc-mods/blame) indicates that the lion den structure isn't registered.

Unregistered structures can easily cause massive issues where other mod worldgen is considered(Blame's mod page has more information), so I would recommend fixing this.

mod version `greekfantasy-16.4.16`

**Comment by skyjay1** [comment]
That shouldn't be happening... I register the feature [here ](https://github.com/skyjay1/GreekFantasy/blob/master/src/main/java/greekfantasy/GFWorldGen.java#L221)(I call the method [here](https://github.com/skyjay1/GreekFantasy/blob/master/src/main/java/greekfantasy/GFWorldGen.java#L180))

**Comment by skyjay1** [comment]
I've located the problem, you can expect a fixed release next week or so
