### ISSUE TITLE
1.16.5 Server Crash - Witch Hunter

### ISSUE THREAD

**Issue by MokahTGS** [skyjay1/GreekFantasy#47]
Getting a server crash when a Witch Hunter killed me.  Crashed the whole server.

Crash Report: https://pastebin.com/cXYLAtQ5

Full Mod List: https://pastebin.com/BaxuyRuX

greekfantasy-16.4.16

**Comment by skyjay1** [comment]
Thanks for the report, I'll have a fixed version uploaded this week
