### ISSUE TITLE
[Request] Protection around villages so no building clips happen with Greekfantasy

### ISSUE THREAD

**Issue by Admiral-Sebastian** [skyjay1/GreekFantasy#49]
Just simple spawn protection of buildings that don't clip with villagers building. There should be a circle around villages and then the structures for Greekfantasy will spawn couple of blocks away from the protection circle of the village

**Comment by skyjay1** [comment]
Because of the generation system I'm using, I'm not sure if it can detect nearby villages, let alone other camps. But I'll see what I can do.

**Comment by Admiral-Sebastian** [comment]
Alrighty :3

**Comment by skyjay1** [comment]
Fixed in 1.18.2 (kinda)
