### ISSUE TITLE
Bug: Creating many Satyr villages on top of Nether

### ISSUE THREAD

**Issue by mactso** [skyjay1/GreekFantasy#5]
In the current release running under 1.16.3 and 1.16.4, many satyr villages are being created on the nether roof.

The campfire area is penetrating the bedrock.

FYI.

**Comment by skyjay1** [comment]
That's strange... the config should be preventing Satyr Camps from appearing in nether biomes...

**Comment by mactso** [comment]
I think I'm using default config but I'll post it in case.

**Comment by skyjay1** [comment]
This should be fixed in the latest release (16.4.3) but if not feel free to re-open this issue.

**Comment by mactso** [comment]
Thank you.
Did you get the server hang bug message I sent you in PM?

**Comment by mactso** [comment]
Will test to see if your new version all fixes the nether hang bug too.

**Comment by mactso** [comment]
This release appears to have fixed the dedicated server "hang" bug. (so far anyway after 8 hours of testing plus checking with the old files that hung).
