### ISSUE TITLE
[Request] makhai and other entity god gifts are marked as pets

### ISSUE THREAD

**Issue by Jackiecrazy** [skyjay1/GreekFantasy#50]
It helps with mods that disable friendly fire or have abilities that boost pets. Without that protection, they feel more like disposable thralls that might even mess up your aim instead of a genuinely helpful ally.

**Comment by skyjay1** [comment]
I'm not sure what "marked as pets" looks like to other mods. My guess is they expect the entity to be a type of TameableEntity, but that automatically makes them AgeableEntity as well and I don't know if I want baby Makhai running around XD
I'll consider it, though

**Comment by Jackiecrazy** [comment]
I suppose baby Makhai could be avoided by manually setting their age to 0 whenever they spawn in and overriding setAge() to always set age to 0? Likewise, console spam from them dying can be suppressed by overriding die().

**Comment by skyjay1** [comment]
Makhai is now a TameableEntity but it may still attack players who are not on the same Team
