### ISSUE TITLE
Arachne Server Crash w/ Alex's Mobs

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#51]
`Minecraft v1.16.5`
`Forge v36.1.9`
`Greek Fantasy v16.4.17`
[`Alex's Mobs v1.10.0`](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)

After the Tarantula Hawk from Alex's Mobs attacked Arachne, I got a server crash.
Previously reported here: Alex-the-666/AlexsMobs#390
[Crash Report](https://gist.github.com/WenXin20/83d79a5ec149e91c0ace83ef5bc0d852)

**Comment by skyjay1** [comment]
It probably has something to do with the fact that Arachne extends the Spider class. I figured this was an easy way to copy all spider behavior but I may need to write my own if problems like this occur.

**Comment by WenXin20** [comment]
Yeah. One interesting thing that came from extending the spider class is that it works with the Spider 2.0 mod.

**Comment by skyjay1** [comment]
Closing this issue as I have made extensive changes to Arachne's code. Please re-open if the problem continues
