### ISSUE TITLE
{Mod compatibility} Crashes when going near to specific satry's camps.

### ISSUE THREAD

**Issue by Jinman269** [skyjay1/GreekFantasy#57]
I don't know what to do but whenever I go to satry camps at specific biomes  (likely modded ones) , it causes crash for me. The likely two culprits of it are terraforged or Oh The Biomes You'll Go; or probably both.

https://pastebin.com/A8Lqfann

**Comment by skyjay1** [comment]
Hmm... there are a couple of mixins that may be interfering. Immersive Engineering is doing something with Vase tile entities and IE and Repurposed Structures are both doing something with the satyr structure. I can't tell exactly what they're doing or why that would cause a crash, though...

**Comment by Jinman269** [comment]
Oh, it's the mixins? I thought it was the biomes or something. I also want to note that I rarely crash when I go to specific satry camps and the crash log always remain the same. Do you need more info?

**Comment by Mr-Syntax** [comment]
ive had it working with everything smoothly except that immersive engineering one so it might be that
