### ISSUE TITLE
Could not serialize greekfantasy.deity.DeityArgument

### ISSUE THREAD

**Issue by kalinzange** [skyjay1/GreekFantasy#58]
Hi,

MC Version: 1.16.5
Forge Version: 36.1.24
Added Datapack Provided: Yes
Mod Version: 16.4.17
DataPack Version: 16.4.17

We are using [ATM6 ModPack (1.6.6)](https://github.com/skyjay1/GreekFantasy/issues/58#issue-906575058) and Added Greek Fantasy Mod to it. Opened a Hosted Server with a friend and changed the following setting to false, whenever I go back and forward from Nether (at least for me) the following error occurred:

Setting:

> #Whether the Shade can steal player XP
> 	shade_attack = false

Console:
[23:20:29] [Netty Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize greekfantasy.deity.DeityArgument@2b7c2a15 (class greekfantasy.deity.DeityArgument) - will not be sent to client!

It makes me suffocate to a wall a couple of times.

Thanks.

**Comment by skyjay1** [comment]
The Netty error happens whenever custom commands are added. Not the source of the bug. Please send the full log.

**Comment by kalinzange** [comment]
Hello,

Server Logs:
[logs.zip](https://github.com/skyjay1/GreekFantasy/files/6566502/logs.zip)

Currently, we are using the server for today's, Debug and the Latest log won't be attached to it.

Thanks!

**Comment by skyjay1** [comment]
I'm unable to find any direct cause of being suffocated in a wall. The server complains that "player kalinzange moved too quickly" but that happens a lot when teleporting is involved. The Netty errors seem to happen whenever the server connects the client to a world but those aren't causing anything in-game. I'm not sure what to tell ya.

**Comment by skyjay1** [comment]
Is this happening in version 16.4.18? If not I can close this issue

**Comment by kalinzange** [comment]
Hii,

I've stopped playing ATM 6, however, I still have the mods and logs on the server and I will update both modpack and Greek Fantasy tomorrow to see if the issue persists and update accordingly here :)

Thanks!

**Comment by kalinzange** [comment]
Hi, 

Quick Update, seems that the error is not generating when I updated the Modpack and Greek's Mod.
