### ISSUE TITLE
[1.16.5] NullPointerException from Entities

### ISSUE THREAD

**Issue by XxInvictus** [skyjay1/GreekFantasy#59]
Client log is being massively spammed by NullPointerExceptions similar to the below
MC 1.16.5
Forge 36.1.24
Greek Fantasy 16.4.17

> [03Jun.2021 07:02:54.642] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
> java.lang.NullPointerException: null
> 	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:205) ~[?:?]
> 	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:137) ~[?:?]
> 	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12) ~[?:?]
> 	at greekfantasy.entity.SatyrEntity.<init>(SatyrEntity.java:96) ~[greekfantasy:16.4.17]
> 	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:445) ~[?:?]
> 	at net.minecraft.entity.EntityType.func_200719_a(EntityType.java:467) ~[?:?]
> 	at net.minecraft.entity.EntityType.func_200717_a(EntityType.java:451) ~[?:?]
> 	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147281_a(ClientPlayNetHandler.java:856) ~[?:?]
> 	at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:90) ~[?:?]
> 	at net.minecraft.network.play.server.SSpawnMobPacket.func_148833_a(SourceFile:14) ~[?:?]
> 	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
> 	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?]
> 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.24-launcher.jar:36.1]
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by skyjay1** [comment]
Unable to reproduce.
