### ISSUE TITLE
1.16.4 Server Crash - Ticking Entity

### ISSUE THREAD

**Issue by MokahTGS** [skyjay1/GreekFantasy#6]
Getting a crash on our server.

Crash Log: https://pastebin.com/aXqjEY54

Ticking a minotaur.

**Comment by skyjay1** [comment]
The issue seems to be caused by com.aavri.craftandhunt.event.FoxThiefEventHandler, likely from a mixin from the Craft And Hunt mod. Please re-open this issue if uninstalling Craft and Hunt does not fix the problem.
