### ISSUE TITLE
Favor and blessing inconsistency

### ISSUE THREAD

**Issue by manhcuongdarma** [skyjay1/GreekFantasy#63]
I'm getting Hades blessing spam in the chat once every minute at level 3 favor but 0 blessings for 5 hours staying at level 10 favor athena.

**Comment by skyjay1** [comment]
Athena does not have blessings by default. She can passively multiply XP orbs that are picked up between levels 4 to 10 and -3 to -10. 
I'll work on nerfing Hades :/
