### ISSUE TITLE
Could not serialize greekfantasy.deity.DeityArgument

### ISSUE THREAD

**Issue by judicius** [skyjay1/GreekFantasy#65]
MC 1.16.5
Forge 36.1.32
Greek Fantasy 16.4.18

https://gist.github.com/judicius/30452988ee55fe2f0f916043097b2edc

**Comment by skyjay1** [comment]
This is a normal warning that happens when Minecraft tries to sync custom commands to the client. It should not affect gameplay in any way whatsoever
