### ISSUE TITLE
Structures don't respect each other and spawn in each other

### ISSUE THREAD

**Issue by judicius** [skyjay1/GreekFantasy#66]
MC 1.16.5
Forge 36.1.32
Greek Fantasy 16.4.18

![2021-07-02_22 31 39](https://user-images.githubusercontent.com/30104638/124340762-7aa99700-db85-11eb-8837-98757b8c6337.png)

**Comment by skyjay1** [comment]
Improved in 1.18.2 (not fully fixed, but less likely to happen)
