### ISSUE TITLE
Enchantment Descriptions Support

### ISSUE THREAD

**Issue by WenXin20** [skyjay1/GreekFantasy#67]
Mod Link: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

Could support for the Enchantment Descriptions mod be added? For support to be added, only `enchantment.greekfantasy.enchant_name.desc` would need to be added to the lang files.

**Comment by skyjay1** [comment]
This has been brought up in the past and I already have support for JEI Enchantment Info by using the `.description` suffix. DarkHax added partial support for this format in Enchantment Descriptions in 7.0.7, see this issue [here](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/52).

I guess I could do a lot of copy-paste to add keys for both `.desc` and `.description` but that would not be ideal.

**Comment by WenXin20** [comment]
Ah, I see. I'll double check to see if it works, it may have just been the logs saying it's missing.
