### ISSUE TITLE
Hades Blessing Makhai Attacking Friends

### ISSUE THREAD

**Issue by Git-Strong** [skyjay1/GreekFantasy#69]
When playing on a server, every time myself or a friend gets attacked, Makhai spawns in and attacks the other friendly player.

I’ve downloaded the data pack and looked through every folder and file, opened them with notepad, and searched “Makhai” or “mak” and can’t find anything with that word. I’ve also combed through them and don’t see anything that relates to the spawning in of Makhai.

It is really annoying and makes boss fights impossible. Can you add a way to disable Makhai or make it so he doesn’t attack players?

If there is a way to do this and I am just missing it please let me know. And thanks for the great mod!

**Comment by skyjay1** [comment]
My apologies, I forgot to add this to the wiki. Use a datapack to change `ares.json` and remove the `"combat_summon_makhai"` entry from `"special_effects"`
See the updated wiki [here](https://github.com/skyjay1/GreekFantasy/wiki/Datapack-support:-Deity#special-favor-effects).
Another solution: Makhai should not attack players/pets who are on the same Team (using scoreboard). I will add a config option to change the spawn chance of mahkai as well
