### ISSUE TITLE
Angry Dryads, or lack there of

### ISSUE THREAD

**Issue by Tyrius1** [skyjay1/GreekFantasy#71]
Dryads dont get angry at the player when the player chops down a tree

greekfantasy-16.4.18
forge 36.2.2
minecraft 1.16.5

make fresh profile, add only greek fantasy, join survival world, stand next to dryad as you break a tree. dryad remains passive.

**Comment by skyjay1** [comment]
I think it has to do with the favor system, since dryads are prevented from being angry when the player has acceptable favor. I'll try to think of a fix...

**Comment by Tyrius1** [comment]
Dunno if this helps at all or if it's related but i was doing some more testing and after summoning in some dryad via /summon command i noticed some significant log spam: Starting at line 13241 it starts freaking out because a satyr camp playing music. it goes away after clearing all entities for about 2 minutes before i decide to test out some dryad behavior and then new dryad spam begins on line 33192
[latest.log](https://github.com/skyjay1/GreekFantasy/files/6978843/latest.log)

**Comment by skyjay1** [comment]
Fixed in 16.5.1
