### ISSUE TITLE
Hydras ignore most spawning rules

### ISSUE THREAD

**Issue by supersaiyansubtlety** [skyjay1/GreekFantasy#78]
Hydras will spawn in light level 15 on a single open fence gate in a void. 
They also spawn in water, redstone, places where they collide with blocks, and on glass, bottom slabs, and bedrock. 
As far as I can tell there's no way to spawn proof an area against hydras other than making it a complete void.

**Comment by skyjay1** [comment]
Oops. I forgot to change line [550](https://github.com/skyjay1/GreekFantasy/blob/master/src/main/java/greekfantasy/GFRegistry.java#L550) . My apologies. This will be fixed in the next version. For now you can turn down the hydra spawn chance in the config.

**Comment by supersaiyansubtlety** [comment]
I'm using [In Control](https://www.curseforge.com/minecraft/mc-mods/in-control) for now to make it some spawning rules. 
I'm enjoying the mod, looking forward to an update!

**Comment by skyjay1** [comment]
This should be fixed in the latest 2 releases.
