### ISSUE TITLE
Gigante spawning issue

### ISSUE THREAD

**Issue by DWX12** [skyjay1/GreekFantasy#82]
Minecraft version - 1.16.5
Mod version - greekfantasy-16.5.3
Modpack - Magical Mischief Tour
https://www.curseforge.com/minecraft/modpacks/magical-mischief-tour

Issue -
Gigantes not spawning in mountains type biomes. Nearly every other mob from this mod has spawned except gigantes. Have tested in single player by upping the spawn rate of them and adding in other biome types. Have had mixed results. My latest test had them spawn in the plains type biome and within a short time of seeing them spawn in, they suddenly disappeared. Checked other biomes and they were no where to be seen. Previous testing with adding them to snowy and cold biome types, had seen them spawn in and stick around, but didn't do extensive enough testing to see how long they stayed. Also had their spawn rates set up to 200.

Just really no clue as to what's going on with just this mob.

**Comment by skyjay1** [comment]
Possibly fixed in 1.18.2. I do not intend to fix 1.16.5
