### ISSUE TITLE
Statues as standalone Decor mod?

### ISSUE THREAD

**Issue by Darkmega18** [skyjay1/GreekFantasy#83]
An old mod called Statues, and then Statues: Rechiseled used to exist for 1.12.2 and before which allowed you to do much of the features that you currently do with your own statues as far as I can tell. Since you allow putting player textures on the statue and posing/equipping of items etc.

I was wondering, would it be possible to get just the statues mechanics split off into a small decorational mod for people to use without all the mobs and other extra content? it would probably be appreciated by some.

In a similar vein, you could probably introduce some mechanics from the original statues rechiseled like being able to make statues out of any stone-like blocks etc too to spice up your own in both this and the standalone too.

**Comment by derabzockerHD** [comment]
You mean this [mod](https://www.curseforge.com/minecraft/mc-mods/statues-rechiseled)

**Comment by Darkmega18** [comment]
yes. but I'm talking in 1.16.5. where it doesn't exist yet. since this mod is 1.16.5 now.

**Comment by skyjay1** [comment]
You can now use RPG Gods for statues, but you will need to use its config to "disable favor" if you don't want the extra load.
