### ISSUE TITLE
Flight enchantment on winged sandals not working

### ISSUE THREAD

**Issue by ryanputraa** [skyjay1/GreekFantasy#85]
I am playing this mod on a Medieval Minecraft modpack server which uses the 1.16.5 3 versions of the mod, as said in the title the flight enchantment you get from Hermes does not work, I have checked the config files of the modpack, and server and both of those have the enchantment enabled, I have also tested it on singleplayer and it did not work sometimes and work some other time.

**Comment by skyjay1** [comment]
I see this issue has been closed, so I'm assuming it has been resolved. If that is not the case, the most common reason is that players forget they need Hermes favor level 10 to use the enchantment, and their favor decreases each day, so they need to make offerings to keep it up. If it's glitchy, taking the sandals off and putting them back on sometimes helps.
