### ISSUE TITLE
[Request] Add a cooldown between Satry trying to ignite campfire

### ISSUE THREAD

**Issue by No3371** [skyjay1/GreekFantasy#9]
Sometimes campfire are getting put out by other mods in certain situation (ex: rain put out campfire, mobs put out light), so that Satry will try to ignite campfire in a row like a machine gun 🤣  Which is bad for performance, wondering if are willing to add a cooldown for this.

**Comment by skyjay1** [comment]
Hmm, there's supposed to be a delay of at least 200 ticks (and it shouldn't even try to light campfires when it's raining) but I'll look into it.

**Comment by No3371** [comment]
In my case, it is the Weeping Angels mod mob put out all lights around it, a Satry just walk up close to the campfire then I heard the flint and steel sound keep firing until the camp fire is ignited. So... yeah it's a issue caused by other mods so It's on you to decide to handle it or not 🆗

**Comment by skyjay1** [comment]
I've added a config option for Satyrs lighting campfires. Turn it off if there are problems.
I've also added a delay between the flint-and-steel sound effects.
