### ISSUE TITLE
 (1.18.2) incompatibility with supplementaries

### ISSUE THREAD

**Issue by 5stigma** [skyjay1/GreekFantasy#99]
incompatibility with supplementaries 1.4.8
version: 18.2.4

[crash-2022-08-22_18.20.59-fml.txt](https://github.com/skyjay1/GreekFantasy/files/9398243/crash-2022-08-22_18.20.59-fml.txt)

**Comment by skyjay1** [comment]
> net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: supplementaries:entity/flags/greekfantasy:spider
Supplementaries is trying to make a flag out of a registered banner pattern, but did not account for modded banners.

**Comment by 5stigma** [comment]
ok, I will try to send a message to Supplementary's developers

**Comment by 5stigma** [comment]
fix set in the last version of Supplementaries.
